### PR TITLE
In case the http server cannot be started the error is logged

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/command/server.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-phoenix/pullRequest?prid=4898962&bid=16221837)

**Review by C0rby — APPROVED** [review]
LGTM

**Review by tboerger — APPROVED** [review]
This got to be added to every ocis extension.

**Comment by DeepDiver1975** [comment]
> This got to be added to every ocis extension.

On it.

**Pull request merged**
