### PR TITLE
Restructure project similar to hello and graph

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/server/debug/server.go  1
- pkg/service/v0/option.go  2
- pkg/service/v0/tracing.go  1
- pkg/server/debug/option.go  2
- pkg/service/v0/logging.go  1
- pkg/metrics/metrics.go  1
- pkg/config/config.go  1
- pkg/server/http/option.go  2
- pkg/flagset/flagset.go  1
- pkg/service/v0/instrument.go  1
- pkg/server/http/server.go  1
- pkg/service/v0/service.go  3
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
+ pkg/command/root.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/owncloud/ocis-phoenix/pullRequest?prid=4630636&bid=15521958)

**Comment by madsi1m** [comment]
--http-root is missing

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/service/v0/logging.go  1
- pkg/server/debug/option.go  2
- pkg/service/v0/instrument.go  1
- pkg/service/v0/tracing.go  1
- pkg/service/v0/service.go  3
- pkg/server/debug/server.go  1
- pkg/service/v0/option.go  2
- pkg/config/config.go  1
- pkg/server/http/option.go  2
- pkg/server/http/server.go  1
- pkg/flagset/flagset.go  1
- pkg/metrics/metrics.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -7
+ pkg/command/root.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/owncloud/ocis-phoenix/pullRequest?prid=4630636&bid=15521958)

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/config/config.go  1
- pkg/service/v0/instrument.go  1
- pkg/server/debug/option.go  2
- pkg/metrics/metrics.go  1
- pkg/service/v0/option.go  2
- pkg/server/http/server.go  1
- pkg/flagset/flagset.go  1
- pkg/service/v0/logging.go  1
- pkg/service/v0/service.go  6
- pkg/service/v0/tracing.go  1
- pkg/server/debug/server.go  1
- pkg/server/http/option.go  2
         

Complexity decreasing per file
==============================
+ pkg/command/server.go  -6
+ pkg/command/root.go  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/owncloud/ocis-phoenix/pullRequest?prid=4630636&bid=15521958)

**Comment by tboerger** [comment]
> --http-root is missing

I have added back this option.

**Comment by tboerger** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 6
           

Complexity increasing per file
==============================
- pkg/service/v0/instrument.go  1
- pkg/metrics/metrics.go  1
- pkg/service/v0/option.go  2
- pkg/service/v0/tracing.go  1
- pkg/flagset/flagset.go  1
- pkg/assets/option.go  1
- pkg/service/v0/service.go  6
- pkg/server/http/server.go  1
- pkg/server/debug/option.go  2
- pkg/server/debug/server.go  1
- pkg/server/http/option.go  2
- pkg/service/v0/logging.go  1
- pkg/config/config.go  1
         

Complexity decreasing per file
==============================
+ pkg/command/root.go  -2
+ pkg/command/server.go  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/owncloud/ocis-phoenix/pullRequest?prid=4630636&bid=15521958)

**Pull request merged**
