### PR TITLE
Embed phoenix and serve it

### PR DESCRIPTION
**Pull request by tboerger**
So far Phoenix have been embedded into the binary and we can customize
the required config based on flags, env variables and optionally via
config file. For now I'm embedding the whole Phonix content, optherwise
the all-in-one binary `ocis` will get pretty complicated until we add
the generate commands to that repo as well and provide a mechanism to
inject the embedding.

### CODE REVIEW

**Comment by tboerger** [comment]
I guess you don't want to review the single file pkg/assets/embed.go as this embeds the whole phoenix content in a compressed way :D

**Comment by butonic** [comment]
```
make generate build
...
go generate github.com/owncloud/ocis-phoenix/pkg/assets
go: downloading golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: extracting golang.org/x/net v0.0.0-20190522155817-f3200d17e092
pkg/assets/assets.go:11: running "gorunpkg": exec: "gorunpkg": executable file not found in $PATH
Makefile:73: die Regel für Ziel „generate“ scheiterte
make: *** [generate] Fehler 1
```
hm
what is gorunpkg? google ... https://github.com/vektah/gorunpkg
read `This repository has been archived by the owner. It is now read-only.` and `ARCHIVED: This is now the default behaviour of go run with go version 1.11+`

```
go version go1.12.3 linux/amd64
```

are you trying to be backwards compatible?

**Comment by tboerger** [comment]
Oh, this haven't been archived when I started to use it. Looks like `go run` can really replace it these days. I have introduced that into my own projects to ensure everybody is using the same version of tools as my work on OSS projects teached me to pin versions as especially linting tools will change behavior which results in different results depending on the used version.

I have replace gorunpkg with `go run` command via ca209f2.

**Review by butonic — APPROVED** [review]
cool I have phoenix running ... now I just need to find the documentation on how to configure it ... ;-)

**Comment by refs** [comment]
Got it up and running smoothly!. Tried to run it with our example `config.json` but didn't like it:

`./ocis-phoenix server --client_id phoenix --config-custom ../../phoenix/config.json`

config.json:

```json
{
  "server" : "http://localhost:9998",
  "theme": "owncloud",
  "version": "0.1.0",
  "openIdConnect": {
    "authority": "http://localhost:9998",
    "metadataUrl": "http://localhost:9998/.well-known/openid-configuration",
    "client_id": "phoenix",
    "client_secret": "foobar",
    "response_type": "code",
    "scope": "openid profile email",
    "extraQueryParams": {
      "claims": "{\"userinfo\":{\"name\":{\"essential\":true},\"preferred_username\":{\"essential\":true},\"email\":{\"essential\":true},\"email_verified\":{\"essential\":true},\"picture\":null}}"
    }
  },
  "apps" : [
    "files", "markdown-editor","pdf-viewer"
  ]
}
```

I'll look into this later. Other than that looks great

**Review by refs — APPROVED** [review]

**Comment by tboerger** [comment]
Do we have a specification for config.json with all available attributes? So far I'm only covering the example config

**Comment by felixboehm** [comment]
can add them later, if we discover more ...
I have issues to understand parts of the code, so need a 10 min training next week ;-)

**Comment by tboerger** [comment]
Merging it now to get the proper Docker image rolling. For now we just provide the flag `--config-file` and the env variable `PHOENIX_CONFIG_FILE` instead of adding flags and env variables for every possible phoenix config option.

**Pull request merged**
