### PR TITLE
Release 0.12.0

### PR DESCRIPTION
**Pull request by kulmann**
Update phoenix assets to 0.15.0

I also added the `clean` step to the release instructions for ocis-phoenix, because I had a message from fileb0x, telling me that switching from 0.14.0 to 0.15.0 didn't cause any changes in the generated assets. Running `make clean generate` instead of just `make generate` caused the assets to be downloaded properly.

### CODE REVIEW

**Comment by kulmann** [comment]
Converted back to a draft, because we need to enable the accounts and settings ui by default now. Will bring that in a separate PR.

**Comment by kulmann** [comment]
Needs a rebase after https://github.com/owncloud/ocis-phoenix/pull/80 got merged

**Comment by kulmann** [comment]
Rebased after https://github.com/owncloud/ocis-phoenix/pull/80 got merged. Now ready for review.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
