### PR TITLE
Prepare release 0.11.0

### PR DESCRIPTION
**Pull request by refs**

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by kulmann** [comment]
This doesn't have the phoenix assets. You have to make a phoenix release first, otherwise an ocis-phoenix release is pointless for ocis 409.

**Comment by PVince81** [comment]
`invalid subdir name changelog/0.11.0-2020-08-17`

replace the first dash with an underscore

**Comment by kulmann** [comment]
I will take over with the 0.14.0 phoenix release assets (as soon as it's done) and will also adapt the changelog path then.

**Comment by kulmann** [comment]
Updated phoenix assets to 0.14.0 and fixed the changelog. Ready for merge.

**Review by PVince81 — APPROVED** [review]
:+1:

**Pull request merged**
